export const BLOG_CATEGORIES = [
  "Lifestyle",
  "Travel",
  "Food & Recipes",
  "Health & Fitness",
  "Personal Development",
  "Self-Care",
  "Parenting",
  "Relationships",
  "Education",
  "Finance & Money",
  "Business & Entrepreneurship",
  "Motivation & Inspiration",
  "Books & Literature",
  "Movies & TV",
  "Anime & Comics",
  "Gaming",
  "Fashion & Beauty",
  "Art & Photography",
  "Music",
  "Science",
  "Environment & Nature",
  "History",
  "Culture",
  "Politics",
  "Sports",
  "Technology",
  "Travel Guides",
  "Hobbies & DIY",
  "Other",
];


